// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slnpptwwrghlmwpkrjib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbnBwdHd3cmdobG13cGtyamliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MzQxMzcsImV4cCI6MjA2MTIxMDEzN30.hLl7tsVC733Ry4FURRBhob-Tc-j-v5ZRorzIuKufU2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);